site_name: k0s Documentation
site_description: Documentation for k0s, the Zero friction Kubernetes distribution.
site_author: Mirantis, Inc.
site_url: https://docs.k0sproject.io
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/k0sproject/k0s
copyright: Copyright &copy; 2021 <a href="https://mirantis.com/">Mirantis Inc.</a>
    - All rights reserved.
edit_uri: ""
nav:
  - Overview: README.md
  - Creating A Cluster:
      - Quick Start Guide: create-cluster.md
      - Run in Docker: k0s-in-docker.md
      - Single node set-up: k0s-single-node.md
      - K0s in Windows (experimental): experimental-windows.md
  - Architecture:
      - Architecture: architecture.md
      - Networking: networking.md
  - Configuration:
      - Configuration Options: configuration.md
      - Configuring Containerd: containerd_config.md
      - Using A Custom CRI: custom-cri-runtime.md
      - Using Cloud Providers: cloud-providers.md
      - Create a cluster with Ansible: examples/ansible-playbook.md
      - Running k0s as a service: install.md
      - IPv4\IPv6 dual-stack networking: dual-stack.md
  - Integrations:
      - Running k0s with Traefik: examples/traefik-ingress.md
      - Running k0s with Ambassador: examples/ambassador-ingress.md
  - CLI Commands:
      - General:            cli/k0s.md
      - k0s api:            cli/k0s_api.md
      - k0s completion:     cli/k0s_completion.md
      - k0s default-config: cli/k0s_default-config.md
      - k0s docs:           cli/k0s_docs.md
      - k0s etcd:           cli/k0s_etcd.md
      - k0s install:        cli/k0s_install.md
      - k0s kubeconfig:     cli/k0s_kubeconfig.md
      - k0s server:         cli/k0s_server.md
      - k0s status:         cli/k0s_status.md
      - k0s token:          cli/k0s_token.md
      - k0s validate:       cli/k0s_validate.md
      - k0s version:        cli/k0s_version.md
      - k0s worker:         cli/k0s_worker.md
  - Deploying Manifests: manifests.md
  - FAQ: FAQ.md
  - Troubleshooting: troubleshooting.md
  - Contributing:
      - Overview: contributors/overview.md
      - Workflow: contributors/github_workflow.md
      - Testing: contributors/testing.md
      - Docs: internal/publishing_docs_using_mkdocs.md
theme:
    name: 'material'
    highlightjs: true
    language: 'en'
    custom_dir: docs/custom_theme
    favicon: https://github.com/k0sproject/k0sproject.github.io/blob/main/images/favicon/favicon.ico
    logo: img/k0s_social.png
    palette:
      - scheme: default
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
      - scheme: slate
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    features:
      - toc.autohide
      - search.suggest
      - search.highlight

extra_css:
  - stylesheets/extra.css
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - toc:
        permalink: "#"
        toc_depth: 3

extra:
    generator: false
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/k0sproject/k0s
        name: k0s on GitHub
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/k0sproject
        name: k0s on Twitter
      - icon: fontawesome/brands/slack
        link: http://k8slens.slack.com/
        name: k0s on Slack
      - icon: fontawesome/solid/link
        link: https://k0sproject.io/
        name: k0s Website
    version:
      method: mike
